apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks-api
  template:
    metadata:
      labels:
        app: stocks-api
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: sankovlex/octozon.stocks:0.1.4
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          command: [ "/bin/sh", "-c", "cat /etc/config/config.yaml && echo && tail -f /dev/null" ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
        volumes:
          - name: config-volume
            configMap:
              name: config-app