apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks-api
  template:
    metadata:
      labels:
        app: stocks-api
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: sankovlex/octozon.stocks:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: StockDbContextSettings__ConnectionString
              value: $(POSTGRES_DB)